// GENERATED by tools/gen_xlive_stub.py — DO NOT EDIT BY HAND.
// Regenerate:  python3 tools/gen_xlive_stub.py
// Gate:        python3 tools/gen_xlive_stub.py --check   (CI)
//
// The XLive surface with libxlive NOT linked: -DCW_XLIVE=OFF drops kernel/xlive_*.cpp from
// the build and compiles this file instead, so every CwXlive_* and Xlive* call site in the
// runtime resolves to the answer xlive_glue.h documents for "no account exists".
//
// THIS IS A BUILD-TIME STATE, NOT A RUNTIME ONE, and the difference matters: CW_NO_XLIVE=1
// at run time reaches the real implementation and asks it to behave as if signed out, which
// is what every measurement of the offline path was taken against. A CW_XLIVE=OFF build
// never had that implementation, so it cannot be used to reproduce one of those
// measurements — it exists for CI and for platforms where the layer is not ported yet. The
// one line it prints at Start says so out loud, because a build that quietly has no
// achievements is a build whose bug reports will be about achievements.
//
// The signatures below are copied verbatim from the headers, and the headers are included,
// so a declaration that drifts is a compile error HERE rather than an undefined symbol in
// somebody's link. 
// 41 functions, copied verbatim from the headers above.

#include "xlive_glue.h"
#include "xlive_session.h"
#include "xlive_social.h"
#include "xlive_stats.h"
#include "xlive_net.h"

#include <cstdio>

// --- xlive_glue.h ------------------------------------------------------
void CwXlive_Start(uint32_t titleId)
{
    // Once, loudly, at the only entry point every boot reaches.
    fprintf(stderr,
            "[xlive] this build has NO libxlive (-DCW_XLIVE=OFF): no account, "
            "no achievements, no session and no leaderboards. Every XLive export "
            "answers as if signed out, which is what xlive_glue.h documents for "
            "CW_NO_XLIVE=1. See tools/gen_xlive_stub.py.\n");
    (void)titleId;
}

bool CwXlive_SignedIn()
{
    return false;
}

bool CwXlive_SignedInToLive()
{
    return false;
}

uint64_t CwXlive_Xuid(uint64_t fallback)
{
    return fallback;
}

const char* CwXlive_Gamertag(const char* fallback)
{
    return fallback;
}

void CwXlive_RecordAchievements(const std::vector<uint16_t>& achievementIds)
{
}

void CwXlive_RecordStats(const std::vector<CwXliveStatView>& views)
{
}

void CwXlive_SetPresence(uint32_t presenceValue)
{
}

void CwXlive_SetPresenceSession(uint64_t sessionId, bool joinable)
{
}

void CwXlive_Shutdown(int timeoutMs)
{
}

// --- xlive_session.h ---------------------------------------------------
void XliveSession_Start()
{
}

void XliveSession_Shutdown()
{
}

bool XliveSession_Enabled()
{
    return false;
}

void XliveSession_SetContext(uint32_t contextId, uint32_t value)
{
}

bool XliveSession_Dispatch(uint32_t message, void* buffer, uint32_t bufferLength, uint32_t overlappedVa, uint32_t* result)
{
    return false;
}

bool XliveSession_PrefetchInviteSession(uint64_t sessionId)
{
    return false;
}

bool XliveSession_InviteSessionInfo(uint64_t sessionId, void* sessionInfoOut)
{
    return false;
}

void XliveSession_DrainSocialTicket(uint64_t ticket)
{
}

uint32_t XliveSession_XnAddrToInAddr(const void* xnaddr)
{
    return 0;
}

bool XliveSession_InAddrToXnAddr(uint32_t inAddr, void* xnaddrOut)
{
    return false;
}

uint64_t XliveSession_PeerForInAddr(uint32_t inAddr)
{
    return 0;
}

uint32_t XliveSession_InAddrForPeer(uint64_t xuid)
{
    return 0;
}

bool XliveSession_LocalXnAddr(void* xnaddrOut)
{
    return false;
}

void XliveSession_SelfTest()
{
}

// --- xlive_social.h ----------------------------------------------------
bool XliveSocial_Dispatch(uint32_t message, void* buffer, uint32_t argumentsVa, uint32_t* result)
{
    return false;
}

bool XliveSocial_Enumerate(uint32_t handle, uint32_t buffer, uint32_t bufferLength, be<uint32_t>* itemsReturned, uint32_t overlappedVa, uint32_t* result)
{
    return false;
}

void XliveSocial_OnFriendsChanged()
{
}

void XliveSocial_OnInviteReceived(uint64_t inviteId, uint64_t fromXuid, uint32_t titleId, uint64_t sessionId, bool accept)
{
}

void XliveSocial_OnInviteSessionReady(uint64_t sessionId, bool ok)
{
}

void XliveSocial_OnConnectionChanged(bool online)
{
}

void XliveSocial_SelfTest()
{
}

bool PostGuestNotification(uint32_t id, uint32_t param)
{
    return false;
}

// --- xlive_stats.h -----------------------------------------------------
void XliveStats_Start()
{
}

void XliveStats_Shutdown()
{
}

bool XliveStats_Enabled()
{
    return false;
}

bool XliveStats_Dispatch(uint32_t message, void* buffer, uint32_t bufferLength, uint32_t overlappedVa, uint32_t* result)
{
    return false;
}

uint32_t XliveStats_CreateEnumerator(uint32_t titleId, uint32_t type, uint64_t pivot, uint32_t rows, uint32_t specCount, const void* specs, be<uint32_t>* sizeOut, be<uint32_t>* handleOut)
{
    return 0;
}

bool XliveStats_Enumerate(uint32_t handle, uint32_t buffer, uint32_t bufferLength, be<uint32_t>* itemsReturned, uint32_t overlappedVa, uint32_t* result)
{
    return false;
}

void XliveStats_SelfTest()
{
}

// --- xlive_net.h -------------------------------------------------------
bool XliveNet_Enabled()
{
    return false;
}

void XliveNet_SelfTest()
{
}
