#!/usr/bin/env bash
# set -e FIRST, before the header comment rather than after it. This script declared it on line 48,
# and line 6 of the header had lost its `#` — so bash ran a line of prose as a command, printed
# "gpu/shader_translator.cpp: No such file or directory" into the build log of a job that then spent
# an hour on an LLVM build, and carried on. With -e in force from line 2 the same mistake stops the
# script at line 6, which is where it is.
set -euo pipefail

# Cross-compile DXC's libdxcompiler.so for Android, into a prefix whose jniLibs/ Gradle packages.
#
# WHY THIS SCRIPT EXISTS, AND WHY IT IS AN LLVM BUILD
# ---------------------------------------------------
# gpu/shader_translator.cpp dlopens `libdxcompiler.so` and calls `DxcCreateInstance` through it. It
# the only compiler in the pipeline: the guest's shader microcode becomes HLSL through XenosRecomp's
# recompiler (compiled into the runtime) and HLSL becomes SPIR-V through DXC (loaded at run time).
# No DXC, no SPIR-V, no draws — the runtime refuses each translation with one log line and presents
# a black screen, which is the failure the first-run check exists to prevent.
#
# THERE IS NO PREBUILT ONE TO DOWNLOAD, and that is not a search that was given up on:
# microsoft/DirectXShaderCompiler publishes `linux_dxc_<date>.x86_64.tar.gz` in every release
# including v1.9.2607 (July 2026), and its arm64 artifacts are Windows `dxcompiler.dll`. The
# `renderbag/dxc-bin` mirror XenosRecomp vendors has the same shape — `lib/x64` and `bin/x64` for
# Linux. So the arm64 library this port needs is a build, not a download.
#
# WHY THE RUNTIME NEEDS IT ON THE PHONE EVEN WITH A COMPLETE CACHE
# ----------------------------------------------------------------
# The desktop release ships a cache and DXC both, and that is not belt-and-braces. D.1 established
# that the disc's `.vo` objects are TEMPLATES the title patches at bind time, so 0 of 104 runtime
# vertex shaders exist verbatim on disc. `tools/release/vs_recipes.bin` — tracked, 107 recipes,
# magic ZCVR, generated by tools/vs_recipes.py from a census of a machine that HAS run the game —
# recovers 102 of them as template+patch, and gpu/shader_prebuild.cpp applies it during the
# first-run pass. That leaves TWO: `vs_539ea9e08aa83f0c` (108 B) and `vs_a4ae7c2b7c1818c4` (60 B),
# which are engine-synthesised, have no template anywhere, and are the 2nd and 4th shaders the
# title ever binds — at boot, before any visible frame. They can only come from the
# translate-on-first-sight path (vk_renderer.cpp's `shaderjit`), which needs DXC on the device.
#
# So a cache built with the recipes is ~1,367 of ~1,369 shaders, and the two that are missing are
# bound before the first frame. That is a black screen with a page of per-shader refusals under one
# easily-missed line, not a small gap: the residue is tiny and it is load-bearing.
#
# WHAT IT COSTS. DXC is an LLVM/Clang fork. This builds the `dxcompiler` shared target only, with
# LLVM_TARGETS_TO_BUILD=None (the cache script's choice — DXC's SPIR-V backend is not an LLVM
# target), tests off, and Release. On a 4-core runner that is tens of minutes; .github/workflows
# caches the build directory so it happens once per DXC pin rather than once per commit.
#
# WHERE THE RESULT GOES. <prefix>/jniLibs/libdxcompiler.so. Gradle packages jniLibs into
# lib/<abi>/, which the framework extracts to nativeLibraryDir (extractNativeLibs is true — see
# app/build.gradle.kts's packaging block), and `HostPaths::ExeDir()` IS nativeLibraryDir on
# Android. `ExeDir()/libdxcompiler.so` is already one of shader_translator.cpp's candidates, so
# this needs no CW_DXC_LIB, no launcher row and no code change: the file being there is the whole
# integration.
#
# Usage:  tools/android/build_dxc.sh [prefix]
#           default third_party/android/<abi>/dxc
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
# shellcheck source=_ndk.sh
. "$HERE/_ndk.sh"

REPO=${CW_DXC_REPO:-https://github.com/microsoft/DirectXShaderCompiler}
# Pinned to a release tag rather than main. DXC's output is not byte-stable across versions, and
# while a cache lookup is keyed on the MICROCODE's hash rather than the compiler's version (so a
# v1.9-built cache and a v1.10-built device translation coexist fine), a moving pin would make
# "the same APK" a different artifact each week for no benefit.
REF=${CW_DXC_REF:-v1.9.2607}
ABI=${CW_ABI:-arm64-v8a}
PREFIX=${1:-$ROOT/third_party/android/$ABI/dxc}
WORK=${CW_DXC_WORK:-/var/tmp/cw-dxc}

# LLVM's link step is the memory-hungry one, not its compile step. Both are capped rather than
# left to -j$(nproc): a dxcompiler link that gets OOM-killed reports as a compiler crash with no
# mention of memory, on a build an hour deep.
JOBS=${CW_DXC_JOBS:-$(nproc)}
LINK_JOBS=${CW_DXC_LINK_JOBS:-2}

echo "==> DirectXShaderCompiler ($REF) for $ABI"
cw_require_ndk "$ABI"

mkdir -p "$WORK"
cd "$WORK"

SRC=$WORK/DirectXShaderCompiler
if [ ! -d "$SRC/.git" ]; then
    echo "==> cloning $REF (shallow — this is an LLVM fork and the history is most of it)"
    git clone --depth 1 --branch "$REF" "$REPO" "$SRC"
else
    echo "==> updating the existing clone"
    git -C "$SRC" fetch --depth 1 origin "refs/tags/$REF:refs/tags/$REF" >/dev/null 2>&1 || true
    # advice.detachedHead off: checking out a tag puts the clone in detached HEAD, which is the
    # intended state here, and git's five lines of advice about it — "Or undo this operation with:
    # git switch -", "Turn off this advice by setting config variable..." — go to stderr, so
    # >/dev/null does not reach them and they land in the middle of a build log. Errors still print.
    git -C "$SRC" -c advice.detachedHead=false checkout "$REF" >/dev/null
fi
git -C "$SRC" log -1 --format='    commit %h  %ad  %s' --date=short

# ALL submodules, not a chosen subset. This named two, SPIRV-Tools and SPIRV-Headers, on the theory
# that googletest is for tests (true, they are off below) and that DirectX-Headers serves the
# DXIL/Windows half, "which does not exist on Android". The theory was wrong, and wrong quietly:
#
#   * include/dxc/Support/D3DReflection.h has an #ifndef _WIN32 branch whose entire purpose is to
#     supply the Windows reflection interfaces to a *nix compile. It includes "d3d12shader.h", which
#     lives in external/DirectX-Headers/include/directx/, and root CMakeLists.txt:685 puts that
#     directory on the include path:
#
#         include_directories(AFTER ${DIRECTX_HEADER_INCLUDE_DIR}/directx
#                                   ${DIRECTX_HEADER_INCLUDE_DIR}/wsl/stubs)
#
#     So the header is a *nix requirement, not a Windows one.
#   * lib/HLSL, which compiles that header into LLVMHLSL, is in the dependency graph of the
#     `dxcompiler` target this script asks for, even though nothing in it is DXIL.
#   * external/CMakeLists.txt guards the requirement with `if(IS_DIRECTORY .../DirectX-Headers)` and
#     an else() FATAL_ERROR — but git leaves an unpopulated submodule as an EMPTY DIRECTORY, so the
#     test passed, DIRECTX_HEADER_INCLUDE_DIR was set to a directory with nothing in it, and the
#     configure that should have refused produced a build that fails at [574/1327] of a step that had
#     by then run forty minutes:
#
#         D3DReflection.h:21:10: fatal error: 'd3d12shader.h' file not found
#
# googletest is dead weight here and costs a few megabytes. The next wrong guess costs an hour.
# SPIRV-Tools needs --recursive for submodules of its own, and a half-populated SPIRV-Tools is a
# configure error naming a header rather than a submodule.
echo "==> submodules (all of them)"
git -C "$SRC" submodule update --init --recursive
for d in external/SPIRV-Tools external/SPIRV-Headers external/DirectX-Headers external/googletest; do
    [ -n "$(ls -A "$SRC/$d" 2>/dev/null)" ] \
        || { echo "FAIL: $d is empty — git -C $SRC submodule update --init --recursive $d" >&2; exit 1; }
done

# Check the FILE, not the directory. A directory is what DXC's own configure tests and what an empty
# submodule provides, which is exactly why that test passed on a tree that could not compile. It is
# checked here rather than after the configure because it is a property of the source tree, and here
# is seconds instead of the forty minutes the build needed to reach the same conclusion.
DXH=$SRC/external/DirectX-Headers/include
if [ ! -f "$DXH/directx/d3d12shader.h" ]; then
    echo "FAIL: $DXH/directx/d3d12shader.h is missing." >&2
    echo "      Every *nix build of DXC includes it through D3DReflection.h, and root" >&2
    echo "      CMakeLists.txt:685 adds $DXH/directx to the include path for it." >&2
    echo "      external/DirectX-Headers contains:" >&2
    { ls -A "$SRC/external/DirectX-Headers" 2>/dev/null | head -5 >&2 || true; }
    exit 1
fi
echo "    d3d12shader.h       $DXH/directx/d3d12shader.h"

BUILD=$WORK/build-$ABI
rm -rf "$BUILD" && mkdir -p "$BUILD"

# ---------------------------------------------------------------------------------------------
# THE HOST HALF OF A CROSS BUILD HAS TO BE CONFIGURED BY HAND, because DXC configures it with three
# flags and none of them is the one its own sources need.
#
# cmake/modules/CrossCompile.cmake ends, at file scope, with
#
#     llvm_create_cross_target_internal(NATIVE "" Release)
#
# which runs, for the tree that will hold the HOST llvm-tblgen and clang-tblgen this cross build
# executes:
#
#     cmake -DCMAKE_BUILD_TYPE=Release -G "$GENERATOR" -DLLVM_TARGETS_TO_BUILD=None "$SRC"
#
# No -C PredefinedParams.cmake, and so no LLVM_ENABLE_EH. LLVM defaults it to OFF, the NATIVE build
# compiles with -fno-exceptions, and DXC's own lib/Support/ErrorHandling.cpp:144 does
# `throw hlsl::Exception(...)`. That is a hard error at [20/134] of a build that is not even the one
# being asked for:
#
#     ErrorHandling.cpp:144:3: error: cannot use 'throw' with exceptions disabled
#
# The same function guards its own configure with `if(NOT IS_DIRECTORY ${LLVM_NATIVE_BUILD})`, so a
# NATIVE tree that already exists is adopted as it stands. Configuring it here is therefore the
# branch DXC's own code offers, not a way around it — and it terminates, because CrossCompile.cmake
# is included only under LLVM_USE_HOST_TOOLS, which the nested configure does not set: it is not
# cross-compiling, it IS the host.
#
# WHICH COMPILER BUILDS THE HOST HALF. The run that produced that error left it to CMake's search,
# and the compile line in its log named
#
#     /usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
#
# Bare, that driver targets the host, and it did compile nineteen files of lib/Support — but file
# twenty was the one that threw, so nothing in that tree ever reached a LINK, and compiling is not
# the half that matters: a driver carrying the NDK's own sysroot and libc++ resolving host headers
# says nothing about it resolving host libraries. The command line was truncated in the only copy of
# that log reachable from here, so how CMake's search arrived at it was never established — and does
# not need to be, because naming a compiler removes the search. Absolute candidates are tried before
# PATH, any resolved path inside an NDK is rejected, and a machine with no host compiler fails here
# with both names printed rather than silently inheriting the one that builds for the phone.
# ---------------------------------------------------------------------------------------------
# What counts as "inside the NDK" is taken from the machine rather than guessed at it: _ndk.sh, which
# this script sourced above and whose cw_require_ndk already ran, sets CW_CLANGXX to the ABI wrapper
# in the NDK's bin/, so that file's directory is precisely the directory to refuse. Path patterns are
# kept as well for a second NDK that _ndk.sh never looked at, and *android-ndk* is among them because
# the standalone zip unpacked to /opt/android-ndk-r27c matches neither `sdk/ndk` nor `ndk-bundle` — a
# gap a dry run of this function found, which is cheaper than the hour-deep run that would have.
NDK_BIN_DIR=$(dirname "${CW_CLANGXX:-/nonexistent}")
pick_host_compiler() {
    local c resolved
    for c in "$@"; do
        [ -n "$c" ] || continue
        resolved=$(command -v "$c" 2>/dev/null) || continue
        case "$resolved" in
            "$NDK_BIN_DIR"/*) continue ;;
            */sdk/ndk/*|*/Sdk/ndk/*|*/ndk-bundle/*|*android-ndk*) continue ;;
        esac
        printf '%s\n' "$resolved"
        return 0
    done
    return 1
}

# A host tool that will not RUN is worse than one that is missing. It is the wrong artifact in
# exactly the right place: DXC finds the file, tries to execute it, and fails an hour into the cross
# build with "cannot execute binary file" in a log about arm64.
#
# The first version of this guard asked the tool for --version and then --help, and treated a refusal
# of both as proof it could not run. It rejected a correctly built x86-64 PIE executable, because
# LLVM's cl library spells options with ONE dash and answered:
#
#     llvm-tblgen: Unknown command line argument '--help'.  Try: 'llvm-tblgen -help'
#
# That line is the tool RUNNING — the very evidence the guard was after, printed in the output the
# guard threw away. A question about executability must not be a question about argument spelling, so
# this classifies by how the execution ended rather than by whether the tool was pleased:
#
#     0        it ran and answered.
#     126      the shell found the file and could not execute it: wrong architecture
#              ("cannot execute binary file: Exec format error") or no permission.
#     127      it was not found, or the dynamic loader could not resolve a library
#              ("error while loading shared libraries") — which is what a tblgen linked against a
#              libc++ that is not on the host produces, and is not a spelling complaint.
#     anything else, the program ran and objected. That is a pass, and its objection is printed,
#              because a guard that hides what it saw is how the last one came to be wrong.
#
# -version is asked first because it is the spelling LLVM's cl library actually accepts, so the
# common case is a clean exit 0 rather than a classified objection.
host_tool_runs() {
    local out status
    out=$("$1" -version 2>&1) && status=0 || status=$?
    case "$status" in
        0)       printf '%s\n' "$out"; return 0 ;;
        126|127) printf '%s\n' "status $status: $out"; return 1 ;;
    esac
    case "$out" in
        *"cannot execute binary file"*|*"Exec format error"*|*"Permission denied"*\
        |*"error while loading shared libraries"*|*"No such file or directory"*)
            printf '%s\n' "status $status: $out"; return 1 ;;
    esac
    printf '%s\n' "ran and answered (status $status): $(sed -n 1p <<<"$out")"
    return 0
}

# `file -b` next to the verdict, so a wrong architecture is named rather than merely reported.
verify_host_tool() {
    local bin=$1 out
    printf '    %-14s %s\n' "$(basename "$bin")" \
        "$(file -b "$bin" 2>/dev/null || echo 'file(1) unavailable')"
    if out=$(host_tool_runs "$bin"); then
        echo "      executes: $(sed -n 1p <<<"$out")"
    else
        echo "FAIL: $bin is there but this machine cannot execute it." >&2
        echo "      DXC's cross build RUNS its host tblgen. Built for the phone, it fails there," >&2
        echo "      an hour deep, in a log that is otherwise entirely about arm64." >&2
        sed -n '1,10p' <<<"$out" >&2
        return 1
    fi
}

HOST_CC=${CW_DXC_HOST_CC:-}
HOST_CXX=${CW_DXC_HOST_CXX:-}
if [ -z "$HOST_CXX" ]; then
    HOST_CXX=$(pick_host_compiler /usr/bin/clang++ /usr/bin/g++ clang++ g++ c++) || HOST_CXX=
fi
if [ -z "$HOST_CC" ]; then
    HOST_CC=$(pick_host_compiler /usr/bin/clang /usr/bin/gcc clang gcc cc) || HOST_CC=
fi
if [ -z "$HOST_CC" ] || [ -z "$HOST_CXX" ]; then
    echo "FAIL: no host compiler outside the NDK (C: '${HOST_CC:-none}', C++: '${HOST_CXX:-none}')." >&2
    echo "      NATIVE/ has to produce tools this machine runs; the NDK's clang produces code for" >&2
    echo "      the phone. Set CW_DXC_HOST_CC and CW_DXC_HOST_CXX to override the search." >&2
    exit 1
fi
echo "==> host compilers for NATIVE/: $HOST_CC / $HOST_CXX"
# A machine that already has host tblgens does not have to build LLVM's, and cmake/modules/
# TableGen.cmake is where that is decided — by testing LLVM_TABLEGEN / CLANG_TABLEGEN against the
# target's own name:
#
#     if( ${${project}_TABLEGEN} STREQUAL "${target}" )                    # TableGen.cmake:95
#         set(${project}_TABLEGEN_EXE "${LLVM_NATIVE_BUILD}/bin/${target}")
#         add_custom_command(OUTPUT ${${project}_TABLEGEN_EXE}
#           COMMAND ${CMAKE_COMMAND} --build . --target ${target} --config Release
#           WORKING_DIRECTORY ${LLVM_NATIVE_BUILD}
#           COMMENT "Building native TableGen...")
#
# So LLVM_TABLEGEN is the input and LLVM_TABLEGEN_EXE is what that block ASSIGNS, with a plain set()
# in function scope that shadows a cache entry of the same name for the rest of the configure. This
# hatch used to pass -DLLVM_TABLEGEN_EXE=: the block overwrote it, the native build ran anyway, and
# the variable did nothing at all. A hatch that silently does not work is worse than no hatch,
# because whoever sets it has said they cannot afford the LLVM build. It takes a DIRECTORY now, since
# these are two different binaries and one path cannot be both.
EXTRA_TABLEGEN=()
if [ -n "${CW_DXC_HOST_TBLGEN_DIR:-}" ]; then
    echo "==> host tblgens from $CW_DXC_HOST_TBLGEN_DIR — NATIVE/ is not built"
    for t in llvm-tblgen clang-tblgen; do
        [ -x "$CW_DXC_HOST_TBLGEN_DIR/$t" ] \
            || { echo "FAIL: $CW_DXC_HOST_TBLGEN_DIR/$t is missing or not executable." >&2; exit 1; }
    done
    EXTRA_TABLEGEN+=("-DLLVM_TABLEGEN=$CW_DXC_HOST_TBLGEN_DIR/llvm-tblgen" \
                     "-DCLANG_TABLEGEN=$CW_DXC_HOST_TBLGEN_DIR/clang-tblgen")
    verify_host_tool "$CW_DXC_HOST_TBLGEN_DIR/llvm-tblgen"
else
    mkdir -p "$BUILD/NATIVE"
    echo "==> configuring the HOST tools DXC's cross build runs (NATIVE/, exceptions and RTTI on)"
    cmake -S "$SRC" -B "$BUILD/NATIVE" -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_COMPILER="$HOST_CC" \
        -DCMAKE_CXX_COMPILER="$HOST_CXX" \
        -DLLVM_TARGETS_TO_BUILD=None \
        -DLLVM_ENABLE_EH=ON \
        -DLLVM_ENABLE_RTTI=ON \
        >"$BUILD/native-configure.log" 2>&1 \
        || { echo "FAIL: the NATIVE (host tools) configure did not complete." >&2
             tail -60 "$BUILD/native-configure.log" >&2; exit 1; }
    EHL=$(grep -m1 '^LLVM_ENABLE_EH:' "$BUILD/NATIVE/CMakeCache.txt" || true)
    if grep -q ':.*=ON$' <<<"$EHL"; then
        echo "    LLVM_ENABLE_EH is ON in NATIVE/CMakeCache.txt"
    else
        echo "FAIL: NATIVE/CMakeCache.txt does not record LLVM_ENABLE_EH=ON, so DXC's" >&2
        echo "      ErrorHandling.cpp will be compiled with -fno-exceptions again." >&2
        echo "      It says: ${EHL:-nothing}" >&2
        exit 1
    fi
    echo "    $(grep -m1 '^CMAKE_CXX_COMPILER:' "$BUILD/NATIVE/CMakeCache.txt" \
        || echo 'NATIVE/CMakeCache.txt records no CMAKE_CXX_COMPILER')"

    # Built here rather than left to the custom command above, for a reason that is entirely about
    # reading a failure: TableGen.cmake drives this build from INSIDE the 1,327-edge cross build, so
    # when it fails the reason arrives as one "FAILED: NATIVE/bin/llvm-tblgen" among unrelated arm64
    # compile lines — which is exactly how two consecutive runs presented an ErrorHandling.cpp error
    # that had nothing to do with arm64. Here it has its own log and its own tail, and by the time
    # DXC asks for the same target it is up to date and the nested command is a no-op.
    # One invocation per target, so a failure names the target rather than leaving two candidates.
    echo "==> building the HOST tools (llvm-tblgen, clang-tblgen)"
    :>"$BUILD/native-build.log"
    for t in llvm-tblgen clang-tblgen; do
        cmake --build "$BUILD/NATIVE" --target "$t" --config Release \
            >>"$BUILD/native-build.log" 2>&1 \
            || { echo "FAIL: the NATIVE build of $t did not complete, and DXC's cross build cannot" >&2
                 echo "      generate a single table without it. Tail of $BUILD/native-build.log:" >&2
                 tail -60 "$BUILD/native-build.log" >&2; exit 1; }
        [ -x "$BUILD/NATIVE/bin/$t" ] \
            || { echo "FAIL: $BUILD/NATIVE/bin/$t is absent after a build that reported success." >&2
                 exit 1; }
    done
    verify_host_tool "$BUILD/NATIVE/bin/llvm-tblgen"
    # clang-tblgen is not executed. It wants a mode argument, so a refusal to run would prove
    # nothing; its architecture is printed instead, and llvm-tblgen — same tree, same driver, same
    # link step — is what proves the host can run what this build produces.
    printf '    %-14s %s\n' clang-tblgen \
        "$(file -b "$BUILD/NATIVE/bin/clang-tblgen" 2>/dev/null || echo 'file(1) unavailable')"
fi

# cmake/caches/PredefinedParams.cmake is DXC's own set of required options, and it is passed with
# -C the way DXC's docs say to: it runs before the root CMakeLists, and the -D flags below override
# it (the cache script cannot override an explicit command-line parameter). What it gives us that
# matters here is LLVM_TARGETS_TO_BUILD=None, LLVM_ENABLE_EH/RTTI=ON and ENABLE_SPIRV_CODEGEN=ON.
# It reaches THIS configure only — hence the NATIVE one above.
echo "==> configuring (tests off, lld, $JOBS compile / $LINK_JOBS link jobs)"
cmake -S "$SRC" -B "$BUILD" -G Ninja \
    -C "$SRC/cmake/caches/PredefinedParams.cmake" \
    -DCMAKE_TOOLCHAIN_FILE="$CW_TOOLCHAIN_FILE" \
    -DANDROID_ABI="$ABI" \
    -DANDROID_PLATFORM="android-$CW_API" \
    -DANDROID_STL=c++_shared \
    -DCMAKE_BUILD_TYPE=Release \
    -DSPIRV_BUILD_TESTS=OFF \
    -DHLSL_INCLUDE_TESTS=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DCLANG_INCLUDE_TESTS=OFF \
    -DLLVM_PARALLEL_COMPILE_JOBS="$JOBS" \
    -DLLVM_PARALLEL_LINK_JOBS="$LINK_JOBS" \
    "${EXTRA_TABLEGEN[@]}" \
    >"$BUILD/configure.log" 2>&1 || { tail -60 "$BUILD/configure.log"; exit 1; }

# c++_shared and not c++_static: the runtime itself is built against c++_shared (AGP's default) and
# the APK ships one libc++_shared.so. A DXC statically linked against its own copy would carry a
# second C++ runtime into one process, which is the classic way to get two heaps and an abort in
# somebody else's destructor.
grep -q 'ANDROID_STL:.*c++_shared' "$BUILD/CMakeCache.txt" \
    || echo "    WARNING: CMakeCache does not record c++_shared — check the STL before shipping."

echo "==> building dxcompiler (this is the long step)"
# -k 20 instead of ninja's default, which stops at the first failing edge. This step is forty-odd
# minutes of a six-hour budget and re-dispatching it is a human action, so the question it has to
# answer is not "does it build" but "how many things are wrong with it": a build that stops at the
# first missing header costs one run per error, and the run that found D3DReflection.h had compiled
# 573 translation units to say one thing. Twenty is enough to tell one cause from several and bounds
# the waste when the cause is catastrophic. On failure every FAILED edge is listed, not just the last
# screenful — grep -m rather than `grep | head`, because head exits on its twentieth line and grep
# dies on the closed pipe, which under the pipefail this script declares reports fewer errors than
# there were.
cmake --build "$BUILD" --target dxcompiler -j"$JOBS" -- -k 20 >"$BUILD/make.log" 2>&1 \
    || { echo "FAIL: the dxcompiler build stopped; $(grep -c '^FAILED:' "$BUILD/make.log" || true) edge(s) failed:" >&2
         grep -m 20 '^FAILED:' "$BUILD/make.log" >&2 || true
         echo "      tail of $BUILD/make.log:" >&2
         tail -60 "$BUILD/make.log" >&2; exit 1; }

# LLVM puts shared libraries in lib/ but the exact path has moved between DXC revisions, so this
# takes the first real file rather than a hardcoded one — and says which it found.
SO=$(find "$BUILD" -name 'libdxcompiler.so*' -type f | head -1)
[ -n "$SO" ] || { echo "FAIL: the build produced no libdxcompiler.so. See $BUILD/make.log" >&2; exit 1; }
echo "    built $SO"

rm -rf "$PREFIX"
mkdir -p "$PREFIX/jniLibs"
cp "$SO" "$PREFIX/jniLibs/libdxcompiler.so"

echo "==> verifying"
DXC=$PREFIX/jniLibs/libdxcompiler.so

# Architecture, from the ELF header rather than from which directory the build ran in: a configure
# that ignored the toolchain file produces host objects, and the failure would otherwise arrive on
# a device as a dlopen error naming a file that is plainly there.
MACHINE=$("$CW_READELF" -h "$DXC" 2>/dev/null \
    | sed -n 's/.*Machine: *//p' | head -1 || true)
if [ -n "$MACHINE" ]; then
    case "$ABI:$MACHINE" in
        arm64-v8a:*AArch64*) : ;;
        x86_64:*X86-64*) : ;;
        *) echo "FAIL: $DXC is $MACHINE but this build asked for $ABI." >&2; exit 1 ;;
    esac
fi

# The one symbol the runtime dlsyms. A libdxcompiler.so that loads but does not export it makes
# LoadDxcOnce skip the candidate and report "no dxcompiler library found" for a file that exists,
# which is a confusing place to end up after an hour of building.
# Here-string, not a pipe: `nm | grep -q` under pipefail reports the symbol missing when it is
# present, because grep -q stops reading the moment it matches and nm dies on a closed pipe. The
# dynamic symbol table here is small enough that it would probably never bite, but a check that is
# correct only for small inputs is a check whose behaviour depends on the thing it verifies.
NMOUT=$("$CW_NM" -D --defined-only "$DXC" 2>/dev/null) \
    || { echo "FAIL: llvm-nm could not read $DXC." >&2; exit 1; }
if ! grep -q 'DxcCreateInstance' <<<"$NMOUT"; then
    echo "FAIL: $DXC does not export DxcCreateInstance." >&2
    echo "      gpu/shader_translator.cpp dlsyms exactly that symbol; without it the library" >&2
    echo "      is skipped and every shader translation is refused." >&2
    exit 1
fi

echo "$REF" > "$PREFIX/version.txt"

echo "==> result"
printf '    %-26s %8s KB\n' "libdxcompiler.so" "$(( $(stat -c%s "$DXC") / 1024 ))"
echo "    architecture          ${MACHINE:-unverified} for $ABI"
echo "    exports               DxcCreateInstance"
echo "    STL                   c++_shared (one C++ runtime in the process, not two)"
echo "OK: $PREFIX"
echo
echo "Package it by pointing Gradle at the jniLibs directory (app/build.gradle.kts does this by"
echo "default for cw.dxcJniLibs). It lands in lib/$ABI/, is extracted to nativeLibraryDir at"
echo "install, and gpu/shader_translator.cpp finds it there as ExeDir()/libdxcompiler.so — no"
echo "CW_DXC_LIB and no launcher row. Verify on a device with:"
echo "    adb logcat -s CaseWest | grep shxlate"
echo "which prints the path it loaded, or the list of candidates it tried and failed."
