#pragma once
// AUTO-GENERATED by tools/gen_vk_shadow.py — DO NOT EDIT BY HAND.
// Regenerate:  python3 tools/gen_vk_shadow.py
// Gate:        python3 tools/gen_vk_shadow.py --check   (CI, .github/workflows/android.yml)
//
// WHAT THIS FILE IS: every Vulkan entry point this runtime calls, as a slot in a table
// that gpu/vk_shadow_android.cpp fills from the loader handle libadrenotools returned —
// plus the #define shadows that bind the existing call sites to those slots without
// touching them. Read the generator's docstring for why Android cannot simply link
// libvulkan, and why the fill happens in two phases.
//
// INCLUDE ORDER IS LOAD-BEARING, exactly as it is in cpu/timebase.h: this header
// includes <vulkan/vulkan.h> FIRST, so the include guard is already set when a
// translation unit that includes both reaches its own <vulkan/vulkan.h> line. Were the
// macros below in scope while the compiler read vulkan_core.h, every declaration inside
// it would be rewritten (`VKAPI_ATTR VkResult VKAPI_CALL CwVk::g_table.vkCreateInstance(...)`)
// and the build would die inside a Khronos header naming neither this file nor Android.
//
// NON-ANDROID BUILDS COMPILE THIS TO NOTHING. The whole file is one #if, so the desktop
// runtime keeps linking Vulkan::Vulkan and every measurement ever taken on it stays
// about the same binary.

#if defined(__ANDROID__)

#include <vulkan/vulkan.h>

namespace CwVk
{

// One X-macro list, used three times: to declare the table, to fill it, and to report
// on it. Three lists that have to agree is a defect waiting for the fourth call site.
#define CWVK_FUNCTION_LIST(X) \
    X(vkAcquireNextImageKHR) \
    X(vkAllocateCommandBuffers) \
    X(vkAllocateDescriptorSets) \
    X(vkAllocateMemory) \
    X(vkBeginCommandBuffer) \
    X(vkBindBufferMemory) \
    X(vkBindImageMemory) \
    X(vkCmdBeginQuery) \
    X(vkCmdBeginRendering) \
    X(vkCmdBindDescriptorSets) \
    X(vkCmdBindIndexBuffer) \
    X(vkCmdBindPipeline) \
    X(vkCmdBindVertexBuffers) \
    X(vkCmdBlitImage) \
    X(vkCmdClearAttachments) \
    X(vkCmdClearColorImage) \
    X(vkCmdClearDepthStencilImage) \
    X(vkCmdCopyBuffer) \
    X(vkCmdCopyBufferToImage) \
    X(vkCmdCopyImage) \
    X(vkCmdCopyImageToBuffer) \
    X(vkCmdDraw) \
    X(vkCmdDrawIndexed) \
    X(vkCmdEndQuery) \
    X(vkCmdEndRendering) \
    X(vkCmdPipelineBarrier) \
    X(vkCmdPushConstants) \
    X(vkCmdResetQueryPool) \
    X(vkCmdResolveImage) \
    X(vkCmdSetBlendConstants) \
    X(vkCmdSetScissor) \
    X(vkCmdSetStencilCompareMask) \
    X(vkCmdSetStencilReference) \
    X(vkCmdSetStencilWriteMask) \
    X(vkCmdSetViewport) \
    X(vkCmdWriteTimestamp) \
    X(vkCreateBuffer) \
    X(vkCreateCommandPool) \
    X(vkCreateDescriptorPool) \
    X(vkCreateDescriptorSetLayout) \
    X(vkCreateDevice) \
    X(vkCreateFence) \
    X(vkCreateGraphicsPipelines) \
    X(vkCreateImage) \
    X(vkCreateImageView) \
    X(vkCreateInstance) \
    X(vkCreatePipelineCache) \
    X(vkCreatePipelineLayout) \
    X(vkCreateQueryPool) \
    X(vkCreateSampler) \
    X(vkCreateSemaphore) \
    X(vkCreateShaderModule) \
    X(vkCreateSwapchainKHR) \
    X(vkDestroyBuffer) \
    X(vkDestroyImage) \
    X(vkDestroyImageView) \
    X(vkDestroyInstance) \
    X(vkDestroySemaphore) \
    X(vkDestroySurfaceKHR) \
    X(vkDestroySwapchainKHR) \
    X(vkDeviceWaitIdle) \
    X(vkEndCommandBuffer) \
    X(vkEnumerateDeviceExtensionProperties) \
    X(vkEnumerateInstanceVersion) \
    X(vkEnumeratePhysicalDevices) \
    X(vkFreeCommandBuffers) \
    X(vkFreeMemory) \
    X(vkGetBufferDeviceAddress) \
    X(vkGetBufferMemoryRequirements) \
    X(vkGetDeviceProcAddr) \
    X(vkGetDeviceQueue) \
    X(vkGetImageMemoryRequirements) \
    X(vkGetInstanceProcAddr) \
    X(vkGetPhysicalDeviceFeatures2) \
    X(vkGetPhysicalDeviceFormatProperties) \
    X(vkGetPhysicalDeviceMemoryProperties) \
    X(vkGetPhysicalDeviceProperties) \
    X(vkGetPhysicalDeviceProperties2) \
    X(vkGetPhysicalDeviceQueueFamilyProperties) \
    X(vkGetPhysicalDeviceSurfaceCapabilitiesKHR) \
    X(vkGetPhysicalDeviceSurfaceFormatsKHR) \
    X(vkGetPhysicalDeviceSurfacePresentModesKHR) \
    X(vkGetPhysicalDeviceSurfaceSupportKHR) \
    X(vkGetPipelineCacheData) \
    X(vkGetQueryPoolResults) \
    X(vkGetSwapchainImagesKHR) \
    X(vkMapMemory) \
    X(vkQueuePresentKHR) \
    X(vkQueueSubmit) \
    X(vkQueueWaitIdle) \
    X(vkResetCommandBuffer) \
    X(vkResetCommandPool) \
    X(vkResetFences) \
    X(vkUpdateDescriptorSets) \
    X(vkWaitForFences)

struct Table
{
#define CWVK_X(fn) PFN_##fn fn = nullptr;
    CWVK_FUNCTION_LIST(CWVK_X)
#undef CWVK_X
};

// How many entry points the list holds. The loader's log line says "N of M resolved", and
// an M that is counted by hand is an M that is wrong the first time someone adds a call —
// which is the exact defect the scan exists to prevent. Straight-line increments are a
// valid constant expression, so this costs nothing at run time.
inline constexpr int FunctionCount()
{
    int n = 0;
#define CWVK_X(fn) ++n;
    CWVK_FUNCTION_LIST(CWVK_X)
#undef CWVK_X
    return n;
}

extern Table g_table;

// Phase 1, before anything creates an instance: dlsym every name out of `loader`
// (adrenotools' hooked libvulkan, or the plain system one when no custom driver is
// selected). Returns the count that resolved; the rest stay null for phase 2.
int InitFromLoader(void* loader);

// Phase 2, once an instance exists: fill whatever phase 1 left null through
// vkGetInstanceProcAddr. Safe to call more than once (a device-loss rebuild creates a
// second instance) and cheap when nothing is missing.
void InitFromInstance(VkInstance instance);

// vkCreateInstance is the ONE entry point that cannot be a bare table slot: it is the
// call that produces the instance phase 2 needs, so it is a hand-written wrapper that
// forwards and then fills. The shadow below points at it, not at the table.
VkResult CreateInstance(const VkInstanceCreateInfo* pCreateInfo,
                        const VkAllocationCallbacks* pAllocator, VkInstance* pInstance);

// One line per unresolved entry point, for the log and for `--diag`. A phone that
// cannot render should say WHICH function is missing, not just that it cannot.
int ReportMissing();

// True once InitFromLoader has run. Every consumer checks this rather than assuming:
// "no loader" and "a loader with a missing entry point" are different failures and
// this runtime has paid for confusing them before (gotcha 5: fail loudly, name it).
bool Ready();

// THE ANDROID HALF, and the only entry point the rest of the runtime needs. Acquires a
// loader — libadrenotools' hooked one when the player selected a custom GPU driver, the
// plain system libvulkan.so otherwise — and fills the table from it. Idempotent, because
// both the bridge and the window module have reasons to want it up before the renderer
// asks, and a second acquire would load a second loader with a second driver table.
// Returns false only when NO loader could be opened, which is "this device has no Vulkan"
// and not "the driver the player picked is broken" — the two are reported separately.
bool InitLoader();

// What InitLoader ended up using: "adrenotools:<libraryName>", "system" or "none". One
// line in the boot log, because a phone that renders with the vendor driver when the
// player believes they selected Turnip is a phone whose performance report is about the
// wrong driver (gotcha 5's other half: say which arm you are in).
const char* LoaderSource();

}  // namespace CwVk

// --- the shadows ---------------------------------------------------------------
// Literal lines, not an X-macro expansion: the preprocessor cannot emit a #define from
// inside a macro, which is the only reason this block is generated rather than written
// once. Sorted, so a diff between two regenerations shows exactly what changed.
//
// CWVK_NO_SHADOW opts out of the macros and keeps the table. Two translation units need
// that: this module's own implementation (which fills the table and must therefore be
// able to name the real functions), and the exported SDL-facing entry points at the
// bottom of it — SDL_Vulkan_LoadLibrary dlsyms `vkGetInstanceProcAddr`, `vkCreateInstance`
// and `vkEnumerateInstance*` BY NAME out of whatever library it is pointed at, so those
// names have to exist as exported symbols here, which a #define would rename away.
#ifndef CWVK_NO_SHADOW
#define vkAcquireNextImageKHR CwVk::g_table.vkAcquireNextImageKHR
#define vkAllocateCommandBuffers CwVk::g_table.vkAllocateCommandBuffers
#define vkAllocateDescriptorSets CwVk::g_table.vkAllocateDescriptorSets
#define vkAllocateMemory CwVk::g_table.vkAllocateMemory
#define vkBeginCommandBuffer CwVk::g_table.vkBeginCommandBuffer
#define vkBindBufferMemory CwVk::g_table.vkBindBufferMemory
#define vkBindImageMemory CwVk::g_table.vkBindImageMemory
#define vkCmdBeginQuery CwVk::g_table.vkCmdBeginQuery
#define vkCmdBeginRendering CwVk::g_table.vkCmdBeginRendering
#define vkCmdBindDescriptorSets CwVk::g_table.vkCmdBindDescriptorSets
#define vkCmdBindIndexBuffer CwVk::g_table.vkCmdBindIndexBuffer
#define vkCmdBindPipeline CwVk::g_table.vkCmdBindPipeline
#define vkCmdBindVertexBuffers CwVk::g_table.vkCmdBindVertexBuffers
#define vkCmdBlitImage CwVk::g_table.vkCmdBlitImage
#define vkCmdClearAttachments CwVk::g_table.vkCmdClearAttachments
#define vkCmdClearColorImage CwVk::g_table.vkCmdClearColorImage
#define vkCmdClearDepthStencilImage CwVk::g_table.vkCmdClearDepthStencilImage
#define vkCmdCopyBuffer CwVk::g_table.vkCmdCopyBuffer
#define vkCmdCopyBufferToImage CwVk::g_table.vkCmdCopyBufferToImage
#define vkCmdCopyImage CwVk::g_table.vkCmdCopyImage
#define vkCmdCopyImageToBuffer CwVk::g_table.vkCmdCopyImageToBuffer
#define vkCmdDraw CwVk::g_table.vkCmdDraw
#define vkCmdDrawIndexed CwVk::g_table.vkCmdDrawIndexed
#define vkCmdEndQuery CwVk::g_table.vkCmdEndQuery
#define vkCmdEndRendering CwVk::g_table.vkCmdEndRendering
#define vkCmdPipelineBarrier CwVk::g_table.vkCmdPipelineBarrier
#define vkCmdPushConstants CwVk::g_table.vkCmdPushConstants
#define vkCmdResetQueryPool CwVk::g_table.vkCmdResetQueryPool
#define vkCmdResolveImage CwVk::g_table.vkCmdResolveImage
#define vkCmdSetBlendConstants CwVk::g_table.vkCmdSetBlendConstants
#define vkCmdSetScissor CwVk::g_table.vkCmdSetScissor
#define vkCmdSetStencilCompareMask CwVk::g_table.vkCmdSetStencilCompareMask
#define vkCmdSetStencilReference CwVk::g_table.vkCmdSetStencilReference
#define vkCmdSetStencilWriteMask CwVk::g_table.vkCmdSetStencilWriteMask
#define vkCmdSetViewport CwVk::g_table.vkCmdSetViewport
#define vkCmdWriteTimestamp CwVk::g_table.vkCmdWriteTimestamp
#define vkCreateBuffer CwVk::g_table.vkCreateBuffer
#define vkCreateCommandPool CwVk::g_table.vkCreateCommandPool
#define vkCreateDescriptorPool CwVk::g_table.vkCreateDescriptorPool
#define vkCreateDescriptorSetLayout CwVk::g_table.vkCreateDescriptorSetLayout
#define vkCreateDevice CwVk::g_table.vkCreateDevice
#define vkCreateFence CwVk::g_table.vkCreateFence
#define vkCreateGraphicsPipelines CwVk::g_table.vkCreateGraphicsPipelines
#define vkCreateImage CwVk::g_table.vkCreateImage
#define vkCreateImageView CwVk::g_table.vkCreateImageView
#define vkCreateInstance CwVk::CreateInstance
#define vkCreatePipelineCache CwVk::g_table.vkCreatePipelineCache
#define vkCreatePipelineLayout CwVk::g_table.vkCreatePipelineLayout
#define vkCreateQueryPool CwVk::g_table.vkCreateQueryPool
#define vkCreateSampler CwVk::g_table.vkCreateSampler
#define vkCreateSemaphore CwVk::g_table.vkCreateSemaphore
#define vkCreateShaderModule CwVk::g_table.vkCreateShaderModule
#define vkCreateSwapchainKHR CwVk::g_table.vkCreateSwapchainKHR
#define vkDestroyBuffer CwVk::g_table.vkDestroyBuffer
#define vkDestroyImage CwVk::g_table.vkDestroyImage
#define vkDestroyImageView CwVk::g_table.vkDestroyImageView
#define vkDestroyInstance CwVk::g_table.vkDestroyInstance
#define vkDestroySemaphore CwVk::g_table.vkDestroySemaphore
#define vkDestroySurfaceKHR CwVk::g_table.vkDestroySurfaceKHR
#define vkDestroySwapchainKHR CwVk::g_table.vkDestroySwapchainKHR
#define vkDeviceWaitIdle CwVk::g_table.vkDeviceWaitIdle
#define vkEndCommandBuffer CwVk::g_table.vkEndCommandBuffer
#define vkEnumerateDeviceExtensionProperties CwVk::g_table.vkEnumerateDeviceExtensionProperties
#define vkEnumerateInstanceVersion CwVk::g_table.vkEnumerateInstanceVersion
#define vkEnumeratePhysicalDevices CwVk::g_table.vkEnumeratePhysicalDevices
#define vkFreeCommandBuffers CwVk::g_table.vkFreeCommandBuffers
#define vkFreeMemory CwVk::g_table.vkFreeMemory
#define vkGetBufferDeviceAddress CwVk::g_table.vkGetBufferDeviceAddress
#define vkGetBufferMemoryRequirements CwVk::g_table.vkGetBufferMemoryRequirements
#define vkGetDeviceProcAddr CwVk::g_table.vkGetDeviceProcAddr
#define vkGetDeviceQueue CwVk::g_table.vkGetDeviceQueue
#define vkGetImageMemoryRequirements CwVk::g_table.vkGetImageMemoryRequirements
#define vkGetInstanceProcAddr CwVk::g_table.vkGetInstanceProcAddr
#define vkGetPhysicalDeviceFeatures2 CwVk::g_table.vkGetPhysicalDeviceFeatures2
#define vkGetPhysicalDeviceFormatProperties CwVk::g_table.vkGetPhysicalDeviceFormatProperties
#define vkGetPhysicalDeviceMemoryProperties CwVk::g_table.vkGetPhysicalDeviceMemoryProperties
#define vkGetPhysicalDeviceProperties CwVk::g_table.vkGetPhysicalDeviceProperties
#define vkGetPhysicalDeviceProperties2 CwVk::g_table.vkGetPhysicalDeviceProperties2
#define vkGetPhysicalDeviceQueueFamilyProperties CwVk::g_table.vkGetPhysicalDeviceQueueFamilyProperties
#define vkGetPhysicalDeviceSurfaceCapabilitiesKHR CwVk::g_table.vkGetPhysicalDeviceSurfaceCapabilitiesKHR
#define vkGetPhysicalDeviceSurfaceFormatsKHR CwVk::g_table.vkGetPhysicalDeviceSurfaceFormatsKHR
#define vkGetPhysicalDeviceSurfacePresentModesKHR CwVk::g_table.vkGetPhysicalDeviceSurfacePresentModesKHR
#define vkGetPhysicalDeviceSurfaceSupportKHR CwVk::g_table.vkGetPhysicalDeviceSurfaceSupportKHR
#define vkGetPipelineCacheData CwVk::g_table.vkGetPipelineCacheData
#define vkGetQueryPoolResults CwVk::g_table.vkGetQueryPoolResults
#define vkGetSwapchainImagesKHR CwVk::g_table.vkGetSwapchainImagesKHR
#define vkMapMemory CwVk::g_table.vkMapMemory
#define vkQueuePresentKHR CwVk::g_table.vkQueuePresentKHR
#define vkQueueSubmit CwVk::g_table.vkQueueSubmit
#define vkQueueWaitIdle CwVk::g_table.vkQueueWaitIdle
#define vkResetCommandBuffer CwVk::g_table.vkResetCommandBuffer
#define vkResetCommandPool CwVk::g_table.vkResetCommandPool
#define vkResetFences CwVk::g_table.vkResetFences
#define vkUpdateDescriptorSets CwVk::g_table.vkUpdateDescriptorSets
#define vkWaitForFences CwVk::g_table.vkWaitForFences
#endif  // CWVK_NO_SHADOW

#endif  // __ANDROID__
